**Fix:** Correct type enforcement error in scheduler
* The aim of this commit is to fix an error that was being thrown when the scheduler ran.

**Error details**
The error was raised by the `@enforce_types()` decorator:

```
TypeError: Argument `batch_size` expected type int | None, got int
```

**What is `enforce_types`?**

`enforce_types` is a decorator that checks the types of parameters at runtime and raises an error if a type does not match the expected one.

**Problem**

The `enforce_types` decorator was raising an error because the method defined an optional parameter (`batch_size: int | None = 500`).
Although the intention was to allow `None` as a possible value, the decorator expected a `NoneType` instead of an `int` when an integer was passed.

**Fix**

The fix was to remove `None` from the type annotation and keep the default parameter value as an integer.

**Previous**

```python
@enforce_types()
def purge_expired_codes(self, retention_days: int = 1, delete_empty_batch: bool = True, batch_size: int | None = 500):

```

**Updated**

```python

@enforce_types()
def purge_expired_codes(self, retention_days: int = 1, delete_empty_batch: bool = True, batch_size: int = 500):

```